# vi:set ft=sh:
#
# Author: Clark WANG <dearvoid at gmail.com>
#

function set_prompt
{
    typeset hostname tty c0=$'\033[0m' c1=$'\033[0;36m'

    hostname=$( hostname )
    hostname=${hostname%%.*}

    tty=$( tty )
    tty=${tty#/dev/}

    PS1="$c1-($c0$USER$c1@$c0$tty$c1)-($c0\$PWD$c1)-"$'\n'"$c1 [$c0\$\$ \$?$c1]$c0 # "
}
set_prompt
